### ISSUE TITLE
Exception: NullPointerException AND IllegalArgumentException

### ISSUE THREAD

**Issue by LewisTehMinerz** [Comprehensive-Minecraft-Archive-Network/CMAN-Java#4]
```
Exception in thread "main" java.lang.NullPointerException
	at javax.swing.ImageIcon.<init>(ImageIcon.java:205)
	at cman.Visual.<init>(Visual.java:107)
	at cman.Inputs.<init>(Inputs.java:35)
	at cman.CMAN.main(CMAN.java:221)
```

-- USING LATEST NIGHTLY BUILD --

**Comment by randomtestfive** [comment]
Latest commit might fix this.

**Comment by LewisTehMinerz** [comment]
Using ImageIO should solve this actually. Good thinking @randomtestfive .

**Comment by LewisTehMinerz** [comment]
Surprisingly, no. Throws an IAE (IllegalArgumentException) saying the input is null...

```
Exception in thread "main" java.lang.IllegalArgumentException: input == null!
	at javax.imageio.ImageIO.read(ImageIO.java:1388)
	at cman.Visual.<init>(Visual.java:110)
	at cman.Inputs.<init>(Inputs.java:35)
	at cman.CMAN.main(CMAN.java:221)
```

**Comment by randomtestfive** [comment]
It's been a while, but this should work now.

**Comment by LewisTehMinerz** [comment]
Note: This issue was written BEFORE the issue template was made. Do not write any issues without using the template or they will be denied without consideration. Only make issues USING THE TEMPLATE.
